# First you need to install https://book.kubebuilder.io/quick-start.html#installation
create-controller-project:
	mkdir -p controller
	cd controller
	go mod init youqin.sun
	kubebuilder init --domain youqin.sun
	kubebuilder create api --group youqin.sun --version v1 --kind DummySite



