---
apiVersion: v1
kind: Service
metadata:
  name: logoutput-svc
  namespace: applications
spec:
  type: LoadBalancer
  selector:
    app: logoutput
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logoutput-configmap
  namespace: applications
data:
    MESSAGE: "Hello"
    pingpong.host:  "pingpong-svc"
    pingpong.port: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-logoutput
          emptyDir: {}
      containers:
        - name: filewriter
          image: lnsth/logoutput1:exercise_4.01
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              cpu: "125m"
            limits:
              memory: "400Mi"
              cpu: "250m"
          volumeMounts:
          - name: shared-logoutput
            mountPath: /files
        - name: output
          image: lnsth/logoutput2:exercise_4.01
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /health
               port: 8080
          resources:
            requests:
              memory: "200Mi"
              cpu: "125m"
            limits:
              memory: "400Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: logoutput-configmap
          volumeMounts:
          - name: shared-logoutput
            mountPath: /files

