apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
  namespace: todo-app-ns
spec:
  metrics:
  - name: cpu-usage-rate
    initialDelay: 10m
    successCondition: result < 0.0021
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1637-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(sum(rate(container_cpu_usage_seconds_total{namespace="todo-app-ns"}[5m])))
