apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- postgres-deployment.yaml
- postgres-secret.yaml
- postgres-service.yaml
- persistentvolumeclaim.yaml
- broadcaster-secret.yaml

images:
- name: be-todos
  newName: lnsth/todo-app-be
  newTag: 8859e4aa634ae2eeb1b519a357139fae0528e499
- name: broadcaster
  newName: lnsth/broadcaster
  newTag: 8859e4aa634ae2eeb1b519a357139fae0528e499
- name: fe-todos
  newName: lnsth/todo-app-fe
  newTag: 8859e4aa634ae2eeb1b519a357139fae0528e499
