apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/postgres-deployment.yaml
- manifests/postgres-secret.yaml
- manifests/postgres-service.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/broadcaster-secret.yaml

images:
- name: fe-todos
  newName: todo-app-fe
- name: be-todos
  newName: todo-app-be
- name: broadcaster
  newName: broadcaster