apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"generation":3,"labels":{"kustomize.toolkit.fluxcd.io/name":"project-kus","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"broadcaster","namespace":"todo-app-ns","resourceVersion":"579356","uid":"4c0ec73b-49d0-4d61-995b-cbf2a31ef73e"},"spec":{"progressDeadlineSeconds":600,"replicas":6,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"broadcaster"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"broadcaster"}},"spec":{"containers":[{"env":[{"name":"CHAT_ID","valueFrom":{"secretKeyRef":{"key":"CHAT_ID","name":"broadcaster-secret"}}},{"name":"BOT_TOKEN","valueFrom":{"secretKeyRef":{"key":"BOT_TOKEN","name":"broadcaster-secret"}}},{"name":"NATS_URL","value":"nats://my-nats.default.svc.cluster.local:4222"}],"image":"lnsth/broadcaster:exercise_4.06","imagePullPolicy":"Always","name":"broadcaster","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":6,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"broadcaster-6bb5cdf56f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":3,"readyReplicas":6,"replicas":6,"updatedReplicas":6}}
    creationTimestamp: "2021-12-10T22:00:20Z"
    generation: 4
    labels:
      kustomize.toolkit.fluxcd.io/name: project-kus
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: broadcaster
    namespace: todo-app-ns
    resourceVersion: "580109"
    uid: 4c0ec73b-49d0-4d61-995b-cbf2a31ef73e
  spec:
    progressDeadlineSeconds: 600
    replicas: 6
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: broadcaster
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        creationTimestamp: null
        labels:
          app: broadcaster
      spec:
        containers:
        - env:
          - name: CHAT_ID
            valueFrom:
              secretKeyRef:
                key: CHAT_ID
                name: broadcaster-secret
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                key: BOT_TOKEN
                name: broadcaster-secret
          - name: NATS_URL
            value: nats://my-nats.default.svc.cluster.local:4222
          image: lnsth/broadcaster:exercise_4.06
          imagePullPolicy: Always
          name: broadcaster
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 6
    conditions:
    - lastTransitionTime: "2021-12-10T22:12:05Z"
      lastUpdateTime: "2021-12-10T22:12:05Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-12-10T22:00:20Z"
      lastUpdateTime: "2021-12-10T22:12:13Z"
      message: ReplicaSet "broadcaster-6bb5cdf56f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 4
    readyReplicas: 6
    replicas: 6
    updatedReplicas: 6
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"generation":3,"labels":{"app":"todo-app","kustomize.toolkit.fluxcd.io/name":"project-kus","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"todo-app","namespace":"todo-app-ns","resourceVersion":"579358","uid":"bb254905-9f23-40ee-a208-84b115ebb343"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"todo-app"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"todo-app"}},"spec":{"containers":[{"env":[{"name":"spring.datasource.url","valueFrom":{"secretKeyRef":{"key":"spring.datasource.url","name":"todoapp-postgress-secret"}}},{"name":"spring.datasource.username","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USER","name":"todoapp-postgress-secret"}}},{"name":"spring.datasource.password","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"todoapp-postgress-secret"}}},{"name":"NATS_URL","value":"nats://my-nats.default.svc.cluster.local:4222"}],"image":"lnsth/todo-app-be:exercise_4.06","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/todo","port":9999,"scheme":"HTTP"},"initialDelaySeconds":90,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"be-todos","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/todo","port":9999,"scheme":"HTTP"},"initialDelaySeconds":90,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"350m","memory":"500Mi"},"requests":{"cpu":"250m","memory":"250Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"image":"lnsth/todo-app-fe:exercise_4.06","imagePullPolicy":"Always","name":"fe-todos","resources":{"limits":{"cpu":"350m","memory":"300Mi"},"requests":{"cpu":"250m","memory":"200Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"todo-app-b5777648d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":3,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    creationTimestamp: "2021-12-10T22:00:20Z"
    generation: 4
    labels:
      app: todo-app
      kustomize.toolkit.fluxcd.io/name: project-kus
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: todo-app
    namespace: todo-app-ns
    resourceVersion: "580111"
    uid: bb254905-9f23-40ee-a208-84b115ebb343
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: todo-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        creationTimestamp: null
        labels:
          app: todo-app
      spec:
        containers:
        - env:
          - name: spring.datasource.url
            valueFrom:
              secretKeyRef:
                key: spring.datasource.url
                name: todoapp-postgress-secret
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: todoapp-postgress-secret
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: todoapp-postgress-secret
          - name: NATS_URL
            value: nats://my-nats.default.svc.cluster.local:4222
          image: lnsth/todo-app-be:exercise_4.06
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /todo
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: be-todos
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /todo
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 350m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: lnsth/todo-app-fe:exercise_4.06
          imagePullPolicy: Always
          name: fe-todos
          resources:
            limits:
              cpu: 350m
              memory: 300Mi
            requests:
              cpu: 250m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-12-10T22:13:26Z"
      lastUpdateTime: "2021-12-10T22:13:26Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-12-10T22:00:20Z"
      lastUpdateTime: "2021-12-10T22:13:26Z"
      message: ReplicaSet "todo-app-b5777648d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 4
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
