apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todoapp-hpa
  namespace: todo-app-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
