name: Release application

on:
  [push, delete]:

jobs:
  delete-environment:
    name: Delete
    runs-on: ubuntu-latest

    steps:
    - name: Delete
      run: |-
        kubectl delete all --all -n ${GITHUB_REF#refs/heads/}
